### ISSUE TITLE
 Make routing information available from the outside

### ISSUE THREAD

**Issue by yukihirop** [yukihirop/r2-oas#135]
## Summary

Currently it is managed by the internal source code, but by adding the structure check code so that it can be safely passed from the outside

https://github.com/yukihirop/r2-oas/blob/7454b8b0f89716b680f9036db5d7a2a259716e6b/lib/r2-oas/schema/v3/generator/base_generator.rb#L40-L43

**Comment by yukihirop** [comment]
## MEMO

Stop loading built-in rake commands with railties

You can load it directly

**Comment by yukihirop** [comment]
## Plan

```rb
R2OAS.configure do |config|
  config.adaptor = :rails
  config.routes_data = fetch_routes do
    Rails.application.reload_routes! 
    Rails.application.reload_routes
  end
end
```

**Comment by yukihirop** [comment]
When trying to take dependence on railties

```
$ be rspec

An error occurred while loading spec_helper. - Did you mean?
                    rspec ./spec/rake_helper.rb

Failure/Error: require 'action_controller/railtie'

LoadError:
  cannot load such file -- rails
# ./vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/railtie.rb:3:in `require'
# ./vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/railtie.rb:3:in `<top (required)>'
# ./spec/spec_helper.rb:5:in `require'
# ./spec/spec_helper.rb:5:in `<top (required)>'
No examples found.
No examples found.


Finished in 0.00003 seconds (files took 0.15947 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Finished in 0.00003 seconds (files took 0.15947 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by webbrain-one** [comment]
Hey! 👋 I've opened PR #208 to address #135. This PR adds a structure check so you can safely pass routing information from the outside. It enables configuration like this:

```ruby
R2OAS.configure do |config|
  config.routes_data = fetch_routes do
    Rails.application.reload_routes! 
    Rails.application.reload_routes
  end
end
```

Let me know what you think! 🙌
